language: php

php:
    - 7.1

cache:
    directories:
        - ~/.composer/cache/files

before_install:
    - phpenv config-rm xdebug.ini || true
    - echo "memory_limit=4096M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
    - composer update --prefer-dist

script:
    - composer validate

    - bin/behat --strict --no-interaction
