sylius_cart_initialize:
    path: /api/cart/init
    methods: [POST]
    defaults:
        _controller: sylius_cart.controller:initializeAction
        _format: json

sylius_cart_add_product:
    path: /api/cart/add-product
    methods: [POST]
    defaults:
        _controller: sylius_cart.controller:addProductAction
        _format: json

sylius_cart_change_product_quantity:
    path: /api/cart/change-product-quantity
    methods: [POST]
    defaults:
        _controller: sylius_cart.controller:changeProductQuantityAction
        _format: json

sylius_cart_remove_product_from_cart:
    path: /api/cart/remove-product
    methods: [POST]
    defaults:
        _controller: sylius_cart.controller:removeProductAction
        _format: json

sylius_cart_clear:
    path: /api/cart/clear
    methods: [POST]
    defaults:
        _controller: sylius_cart.controller:clearAction
        _format: json
